services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: php-apache-time-test
    container_name: php-apache-time-test-container
    ports:
      - "8080:80"
    extra_hosts:
      - "nsk.time.test:127.0.0.1"
      - "l-a.time.test:127.0.0.1"